stages:
  - build
  - debug
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com/gwynbliedd1/webapp-deploy
  # If your deploy token name is 'ci-registry' for example
  CI_DEPLOY_USER: gwynbliedd1    # The username shown in deploy token
  CI_DEPLOY_PASSWORD:  gldt-s-P5uiyza1wDpgeQvPzu # The token value

# build_images:
#   stage: build
#   image: docker:20.10.16
#   services:
#     - docker:20.10.16-dind
#   before_script: [
#     'echo "Registry: $CI_REGISTRY"',
#     'echo "Registry User: $CI_DEPLOY_USER"',
#     'echo "Docker Registry: $DOCKER_REGISTRY"',
#     'echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin'
#   ]
#   script:
#     - docker build -t $DOCKER_REGISTRY/frontend:latest ./dockerfiles/frontend
#     - docker build -t $DOCKER_REGISTRY/backend:latest ./dockerfiles/backend
#     - docker build -t $DOCKER_REGISTRY/mysql:latest ./dockerfiles/mysql
#     - docker push $DOCKER_REGISTRY/frontend:latest
#     - docker push $DOCKER_REGISTRY/backend:latest
#     - docker push $DOCKER_REGISTRY/mysql:latest
debug_k8s:
  stage: debug
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    # Debug steps
    - echo "Checking if KUBE_CONFIG variable exists:"
    - if [ -n "$KUBE_CONFIG" ]; then echo "KUBE_CONFIG is set"; else echo "KUBE_CONFIG is not set"; fi
    - echo "Decoding and saving kubeconfig:"
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yaml
    - echo "Checking kubeconfig file content:"
    - cat kubeconfig.yaml
    - echo "Setting KUBECONFIG environment variable:"
    - export KUBECONFIG=kubeconfig.yaml
    - echo "Current working directory:"
    - pwd
  script:
    - kubectl config view
    - kubectl get nodes

deploy_to_k8s:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yaml
    - export KUBECONFIG=kubeconfig.yaml
        # Add these debug commands
    - kubectl config view
    - kubectl get nodes
  script:
    # Create MySQL password secret
    - kubectl create secret generic mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=SecurePassword --dry-run=client -o yaml | kubectl apply -f -
    # Apply Kubernetes manifests
    - kubectl apply -f k8s/db-yamls/
    - kubectl apply -f k8s/backend-yamls/
    - kubectl apply -f k8s/frontend-yamls/
    - kubectl apply -f k8s/ingress-yamls/
#  only:
#    - main